### ISSUE TITLE
ext4

### ISSUE THREAD

**Issue by depesh1977** [RadGoodNowYT/android_device_tecno_KG5n#1]
[так у тебя](https://github.com/RadGoodNowYT/android_device_tecno_KG5n/blob/569ce7d2f5d1bc40f67c3887b952dc0c239361ef/BoardConfig.mk#L102)
а должно быть
`# FILESYSTEMS
TARGET_USERIMAGES_USE_F2FS := true

TARGET_USERIMAGES_USE_EXT4 := true`
дополни..это обязательно и как ты не заметил

**Comment by Arturmes** [comment]
I didn't notice, we'll fix it now
